### PR TITLE
Fix #217. Use Appraisal to test the gem

### LINKED ISSUE #217: Using appraisal to test the gem against many versions
I was wondering in starting to use [appraisal](https://github.com/thoughtbot/appraisal) to test the gem against different versions of the mongoid without depends on the env `MONGOID_VERSION`. It could be the next step.

### PR DESCRIPTION
**Pull request by javierav**

### CODE REVIEW

**Comment by dblock** [comment]
I would merge this on 🟢

**Comment by javierav** [comment]
@dblock ready!

**Comment by dblock** [comment]
Thanks, check out #196 pls.

**Comment by dblock** [comment]
Thanks, check out https://github.com/mongoid/mongoid-rspec/issues/237 if you want to take on some maintenance/release of this gem.

**Pull request merged**
