### PR TITLE
Add support for if/unless validator options

### PR DESCRIPTION
**Pull request by knovoselic**
This PR adds support for testing validators which are triggered only under a certain condition. The change supports if/unless options with symbol or lambda parameters as the conditions.

### CODE REVIEW

**Comment by dblock** [comment]
Definitely need to fix CI first.

**Comment by dblock** [comment]
@knovoselic interested in helping out with maintaining this library? If @rodrigopinto doesn't object I can add you here and rubygems.

**Comment by dblock** [comment]
Maybe you can finish https://github.com/mongoid/mongoid-rspec/pull/216 too? :)

**Comment by johnnyshields** [comment]
FYI, this PR broke semver of this gem as it was released as 4.2.0 (tiny version bump)--it caused many of my existing test cases to fail.

I have merged a PR here: https://github.com/mongoid/mongoid-rspec/pull/249 which now gates it behind a `.check_conditions` method.

I am lukewarm on the idea of making this "check_conditions" logic to be the default behavior. If we were to do it, it would need to (a) be done in a major release, i.e. 5.0.0, and (b) we would have to handle it very carefully. Read this comment for details:
https://github.com/mongoid/mongoid-rspec/pull/249#issuecomment-4370146508

**Comment by dblock** [comment]
Agreed @johnnyshields I think a 5.0 with default behavior makes sense.

**Pull request merged**
