### PR TITLE
Add support for `optional` in relations matchers

### PR DESCRIPTION
**Pull request by javierav**

### CODE REVIEW

**Comment by dblock** [comment]
This needs a README update, too, right?

**Comment by davekrupinski** [comment]
Could this be merged in if the changelog conflict is resolved?

**Comment by dblock** [comment]
Yes please.

**Comment by davekrupinski** [comment]
@dblock https://github.com/mongoid/mongoid-rspec/pull/236

**Comment by javierav** [comment]
@dblock Merge updated! :)

**Pull request merged**
