### PR TITLE
Migration from TravisCI to GitHub Actions

### PR DESCRIPTION
**Pull request by skalibog**
I succesfully migrate to GHA.
With these items I have my doubts and need help to fix:
- Update gemspec.
-  Changes in code. Remove deprecated functionality, nothing changed. IDK how correct create this PR.
- Danger token. I was put into repo secrets and use in CI step.
Any help in completing this PR would be appreciated.

### CODE REVIEW

**Comment by dblock** [comment]
Pickup a danger token from https://github.com/mongoid/mongoid-locker/tree/master/.github/workflows, PRs don't have access to secrets.

**Comment by dblock** [comment]
Do you have a passing CI on your fork? Post link. Add a badge to README. Thanks!

**Comment by skalibog** [comment]
@dblock Hey, yes all passing well.
Here is the following links:
Actions: https://github.com/skalibog/mongoid-rspec/actions
README: https://github.com/skalibog/mongoid-rspec/tree/feature/migrate-ci-to-gha
Badges not working well, cause it is references to mongoid/mongoid-rspec without GHA. After merge all will be good.
And I added a rubocop badge.

**Comment by dblock** [comment]
Thanks for doing this! There are other projects in the mongoid org that could use the same :)

**Pull request merged**
