### PR TITLE
Re-add support for `ordered_by` matcher for Mongoid 5 and older

### LINKED ISSUE #214: uninitialized constant Mongoid::Contextual::Queryable::Key
I'm using mongoid 5.1.6 and mongoid-rspec 4.0.0 and I have the following error:

```
     NameError:
       uninitialized constant Mongoid::Contextual::Queryable::Key
```

with the following spec:

```ruby
  describe 'Embeds' do
    it { is_expected.to embed_many(:preparation_rows).ordered_by('order_number ASC') }
  end
```

This was working fine with mongoid-rspec 3.x.

I guess the version 4.0.0 is not compatible with mongoid 5?

If so, I guess the [`s.add_dependency 'mongoid', '>= 3.1'`](https://github.com/mongoid/mongoid-rspec/blob/master/mongoid-rspec.gemspec#L21) should be changed so that it requires the compatible version of mongoid.

### PR DESCRIPTION
**Pull request by stim371**
The PR to support Mongoid 6 removed a conditional to select the correct
location for the Key class.

Fixes #214

## Question for Maintainer
This PR fails a rubocop check for Class length. Curious if you'd like to try to golf the class or extend/ignore the rubocop check.

### CODE REVIEW

**Comment by dblock** [comment]
For rubocop just run `rubocop -a ; rubocop --auto-gen-config`, we only care about auto-correctable things.

**Comment by dblock** [comment]
Thanks for fixing this, will merge on green.

**Comment by stim371** [comment]
Thanks, @dblock . Should be all set!

**Comment by zedtux** [comment]
Thank you @stim371 ! 🎉

**Comment by zedtux** [comment]
@dblock will you release a new version of this gem soon?

**Comment by dblock** [comment]
I can, but this gem really could use some more maintainers. Maybe @stim371 wants to join? If yes what's your rubygems email, I'll grant you access.

**Comment by stim371** [comment]
@dblock I see a number of open issues that might be interesting to try to pick off, but I'm about to move away from mongoid (switching orgs), so I don't think I'd be a very active/invested maintainer for the long term.

**Comment by zedtux** [comment]
Lucky you are @stim371 😏

**Comment by dblock** [comment]
Thanks @stim371, no worries. Also MongoDB is great, I don't know what ya'll talking about :)

**Pull request merged**
